### PR TITLE
fixing async tests

### LINKED ISSUE #484: Silently failing sw-background-sync-queue tests
**Library Affected**:
*sw-background-sync-queue*

While rewriting the build process, I was examining the tests for `sw-background-sync-queue` to make sure they continued to pass. I noticed that in the current `master` branch there are a number of failures that are logged to the JS console during test execution; they appear to the "silent" in that they don't cause any of the tests to fail. It's hard to copy the JS console text, but here's a screenshot from the current Chrome stable:

screen shot 2017-05-01 at 10 26 20 pm

### PR DESCRIPTION
**Pull request by prateekbh**
R: @jeffposnick 

Fixes #484 

Two of the async tests did not returned the promise back, which was failing the assertion.

### CODE REVIEW

File: packages/sw-background-sync-queue/test/browser/background-sync-queue.js [hunk 1]
```diff
@@ -63,16 +63,16 @@ describe('background sync queue test', () => {
 
   it('check push proxy', () => {
     const currentLen = backgroundSyncQueue._queue.queue.length;
-    backgroundSyncQueue.pushIntoQueue({request: new Request('http://lipsum.com')}).then( (e) => {
-      chai.assert.equal(backgroundSyncQueue._queue.queue.length,
+    return backgroundSyncQueue.pushIntoQueue({request: new Request('http://lipsum.com')}).then( (e) => {
+      return chai.assert.equal(backgroundSyncQueue._queue.queue.length,
```
Comment (jeffposnick) [inline packages/sw-background-sync-queue/test/browser/background-sync-queue.js]: I don't think `chai.assert.*` has a return value, so `return`ing it here isn't accomplishing anything.

File: packages/sw-background-sync-queue/test/browser/background-sync-queue.js [hunk 2]
```diff
@@ -63,16 +63,16 @@ describe('background sync queue test', () => {
...
         currentLen + 1);
     });
   });
 
   it('check fetchDid fail proxy', () => {
     const currentLen = backgroundSyncQueue._queue.queue.length;
-    backgroundSyncQueue.fetchDidFail({request: new Request('http://lipsum.com')}).then( (e) => {
-      chai.assert.equal(backgroundSyncQueue._queue.queue.length,
+    return backgroundSyncQueue.fetchDidFail({request: new Request('http://lipsum.com')}).then( (e) => {
+      return chai.assert.equal(backgroundSyncQueue._queue.queue.length,
```
Comment (jeffposnick) [inline packages/sw-background-sync-queue/test/browser/background-sync-queue.js]: I don't think `chai.assert.*` has a return value, so `return`ing it here isn't accomplishing anything.

File: packages/sw-background-sync-queue/test/browser/background-sync-queue.js [hunk 3]
```diff
@@ -63,16 +63,16 @@ describe('background sync queue test', () => {
 
   it('check push proxy', () => {
```
Comment (jeffposnick) [inline packages/sw-background-sync-queue/test/browser/background-sync-queue.js]: Consider marking this function as `async`, and then you can do

```js
await backgroundSyncQueue.pushIntoQueue({request: new Request('http://lipsum.com')});
chai.assert.equal(...);
```

See, e.g., https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-runtime-caching/test/sw/request-wrapper.js#L214

That might make it clearer that you're not actually using the value that the first promise resolves with, and also clarify that the assertion doesn't return a value.

File: packages/sw-background-sync-queue/test/browser/background-sync-queue.js [hunk 4]
```diff
@@ -61,17 +61,17 @@ describe('background sync queue test', () => {
       CALLBACKS);
   });
 
-  it('check push proxy', () => {
+  it('check push proxy', async () => {
     const currentLen = backgroundSyncQueue._queue.queue.length;
-    backgroundSyncQueue.pushIntoQueue({request: new Request('http://lipsum.com')}).then( (e) => {
+    await backgroundSyncQueue.pushIntoQueue({request: new Request('http://lipsum.com')}).then( (e) => {
```
Comment (jeffposnick) [inline packages/sw-background-sync-queue/test/browser/background-sync-queue.js]: `await` is an alternative to attaching a `.then()`.

So this could be:

```js
await backgroundSyncQueue.pushIntoQueue({request: new Request('http://lipsum.com')});
chai.assert(...);
```

That will block until `pushIntoQueue()` completes, and then execute the assertion. Again, it's just an alternative to using `.then()`, but I think it ends up be clearer, especially for cases when you're ignoring the value that the async operation resolves with (like you are in this case).

File: packages/sw-background-sync-queue/test/browser/background-sync-queue.js [hunk 5]
```diff
@@ -61,17 +61,17 @@ describe('background sync queue test', () => {
...
       chai.assert.equal(backgroundSyncQueue._queue.queue.length,
         currentLen + 1);
     });
   });
 
-  it('check fetchDid fail proxy', () => {
+  it('check fetchDid fail proxy', async () => {
     const currentLen = backgroundSyncQueue._queue.queue.length;
-    backgroundSyncQueue.fetchDidFail({request: new Request('http://lipsum.com')}).then( (e) => {
+    await backgroundSyncQueue.fetchDidFail({request: new Request('http://lipsum.com')}).then( (e) => {
```
Comment (jeffposnick) [inline packages/sw-background-sync-queue/test/browser/background-sync-queue.js]: Ditto re: removing the `.then()`.

File: packages/sw-background-sync-queue/test/browser/background-sync-queue.js (hunk 4 above)
Comment (prateekbh) [inline packages/sw-background-sync-queue/test/browser/background-sync-queue.js]: done

File: packages/sw-background-sync-queue/test/browser/background-sync-queue.js (hunk 5 above)
Comment (prateekbh) [inline packages/sw-background-sync-queue/test/browser/background-sync-queue.js]: done

**Comment by jeffposnick** [comment]
The changes look okay—just to confirm, though, there are still some errors logged in the console when running the modified code. Are they to be expected/safe to ignore?

screen shot 2017-05-02 at 1 30 35 pm

**Comment by prateekbh** [comment]
@jeffposnick most of them yes!
I've added dummy calls which does not even support Cross domain XHR. Although adding them immediately fires the call and causes some errors.
Ill revisit to minimize these, however its cool if they stay for a while
